services:
  mysql:
    image: mysql:8.0
    container_name: movie_db  
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: root  
      MYSQL_USER: root 
      MYSQL_PASSWORD: root
    volumes:
      - movie_db:/var/lib/mysql
    ports:
      - "3300:3306"

volumes:
  movie_db:
